version: "2"

services:
  logstash-1:
    hostname: "logstash-1"
    build: ./logstash
    environment:
      # Pipelines configuration
      - "ELASTICSEARCH_HOSTS=ingest-1"
    networks:
      - backend
    ports:
      - "127.0.0.1:8080:8080"

  master-1:
    hostname: "master-1"
    build: ./elasticsearch_master
    environment:
      # System and Java configuration
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1000m -Xmx1000m"
      # Node configuration
      - "node.name=master-1"
      - "cluster.name=mine42"
      - "discovery.seed_hosts=master-1"
      - "cluster.initial_master_nodes=master-1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "master-1:/usr/share/elasticsearch/data"
      - "/data/elastic-searchguard-tls:/usr/share/elasticsearch/searchguard-tls/"
    networks:
      - backend 

  ingest-1:
    hostname: "ingest-1"
    build: ./elasticsearch_ingest
    environment:
      # System and Java configuration
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms500m -Xmx500m"
      # Node configuration
      - "node.name=ingest-1"
      - "cluster.name=mine42"
      - "discovery.seed_hosts=master-1"
      - "cluster.initial_master_nodes=master-1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "ingest-1:/usr/share/elasticsearch/data"
      - "/data/elastic-searchguard-tls:/usr/share/elasticsearch/searchguard-tls/"
    networks:
      - backend
    ports:
      - "127.0.0.1:9200:9200/tcp"
    depends_on:
      - master-1
      - data-1
      - data-2

  data-1:
    hostname: "data-1"
    build: ./elasticsearch_data
    environment:
      # System and Java configuration
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms3000m -Xmx3000m"
      # Node configuration
      - "node.name=data-1"
      - "cluster.name=mine42"
      - "discovery.seed_hosts=master-1"
      - "cluster.initial_master_nodes=master-1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "data-1:/usr/share/elasticsearch/data"
      - "/data/elastic-searchguard-tls:/usr/share/elasticsearch/searchguard-tls/"
    networks:
      - backend
    depends_on:
      - master-1

  data-2:
    hostname: "data-1"
    build: ./elasticsearch_data
    environment:
      # System and Java configuration
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms3000m -Xmx3000m"
      # General configuration
      - "node.name=data-2"
      - "cluster.name=mine42"
      - "discovery.seed_hosts=master-1"
      - "cluster.initial_master_nodes=master-1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "data-2:/usr/share/elasticsearch/data"
      - "/data/elastic-searchguard-tls:/usr/share/elasticsearch/searchguard-tls/"
    networks:
      - backend
    depends_on:
      - master-1

  kibana-1:
    hostname: "kibana-1"
    build: ./kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://data-1:9200"
    # volumes:
    #   - "/data/elastic-searchguard-tls:/usr/share/elasticsearch/searchguard-tls/"
    networks:
      - backend
    ports:
      - "127.0.0.1:5601:5601/tcp"



networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
  

volumes:
  master-1:
    driver: local

  ingest-1:
    driver: local

  data-1:
    driver: local

  data-2:
    driver: local
