version: "2"

services:
  # logstash-1:
  #   hostname: "logstash-1"
  #   build: ./logstash
  #   environment:
  #     # Pipelines configuration
  #     - "ELASTICSEARCH_HOSTS=ingest-1"
  #   networks:
  #     - backend
  #   ports:
  #     - "127.0.0.1:8080:8080"

  security:
    hostname: "security"
    build: ./elasticsearch_security
    volumes:
      - "/data/elastic/certs:/usr/share/elasticsearch/config/certs"
      - "${PWD}/passwords:/usr/share/elasticsearch/config/passwords"
    networks:
      - backend

  ingest-1:
    hostname: "ingest-1"
    build: ./elasticsearch_ingest
    environment:
      - "ES_JAVA_OPTS=-Xms500m -Xmx500m"
      - "discovery.seed_hosts=master-1"
      - "cluster.initial_master_nodes=master-1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/data/elastic/ingest-1:/usr/share/elasticsearch/data"
      - "/data/elastic/certs:/usr/share/elasticsearch/config/certs"
    networks:
      - backend
    ports:
      - "127.0.0.1:9200:9200/tcp"

  master-1:
    hostname: "master-1"
    build: ./elasticsearch_master
    environment:
      - "ES_JAVA_OPTS=-Xms1000m -Xmx1000m"
      - "discovery.seed_hosts=master-1"
      - "cluster.initial_master_nodes=master-1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/data/elastic/master-1:/usr/share/elasticsearch/data"
      - "/data/elastic/certs:/usr/share/elasticsearch/config/certs"
    networks:
      - backend
    depends_on:
      - ingest-1

  data-1:
    hostname: "data-1"
    build: ./elasticsearch_data
    environment:
      - "ES_JAVA_OPTS=-Xms3000m -Xmx3000m"
      - "discovery.seed_hosts=master-1"
      - "cluster.initial_master_nodes=master-1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/data/elastic/data-1:/usr/share/elasticsearch/data"
      - "/data/elastic/certs:/usr/share/elasticsearch/config/certs"
    networks:
      - backend
    depends_on:
      - master-1

  data-2:
    hostname: "data-1"
    build: ./elasticsearch_data
    environment:
      - "ES_JAVA_OPTS=-Xms3000m -Xmx3000m"
      - "discovery.seed_hosts=master-1"
      - "cluster.initial_master_nodes=master-1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/data/elastic/data-2:/usr/share/elasticsearch/data"
      - "/data/elastic/certs:/usr/share/elasticsearch/config/certs"
    networks:
      - backend
    depends_on:
      - master-1

  kibana-1:
    hostname: "kibana-1"
    build: ./kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://data-1:9200"
    networks:
      - backend
    ports:
      - "127.0.0.1:5601:5601/tcp"
    depends_on:
      - master-1
      - data-1
      - data-2


networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
