# Memory control
bootstrap.memory_lock: true

# Network discovery
network.host: _site_

# Node properties
node:
  master: false
  data: true
  ingest: false
  name: ${HOSTNAME}

# Cluster properties
cluster.name: elastic

# X-Pack properties
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: certs/elastic-certificates.p12