node.name: ${HOSTNAME}

config.reload:
    automatic: false

# Queue properties
queue.type: persisted
queue.max_bytes: 1gb

# X-Pack properties
xpack.monitoring:
  enabled: true
  collection.enabled: true
  elasticsearch.ssl.certificate_authority: config/certs/elastic-stack-ca.pem
  # elasticsearch.hosts: ["https://data-1:9200", "https://data-2", ...]